### ISSUE TITLE
request_headers

### ISSUE THREAD

**Issue by bubbaspaarx** [proxycrawl/proxycrawl-ruby#1]
Is there any way to add request_headers into the options for the request? I can do it manually using the standard api url

https://api.proxycrawl.com/?token=YOUR_TOKEN&url=https://httpbin.org/headers&request_headers=Accept-Language%3Aen-GB

but adding them to the options section for the gem doesn't appear to work

**Comment by crawlbase** [comment]
@bubbaspaarx Thanks for your request.

The `request_headers` param is already supported at this gem and you should be able to use it similar to any other option (API param). Check its documentation at the below link and let us know if you would like us to whitelist a special request header for a specific website.

https://proxycrawl.com/docs/crawling-api/parameters#request-headers

In addition, see below a coding example of how to use and test the request headers with our API:

```ruby
[1] pry(main)> api = ProxyCrawl::API.new(token: YOUR_TOKEN)
=> #<ProxyCrawl::API:0x00007fc1c7ba6798 @token="YOUR_TOKEN">

[2] pry(main)> JSON.parse(api.get('https://httpbin.org/headers').body)
=> {"headers"=>{
  ...
  "Accept-Language"=>"en-US,en;q=0.9",
  "Referer"=>"https://httpbin.org"
  ...
}}

[3] pry(main)> JSON.parse(api.get('https://httpbin.org/headers', { request_headers: 'referer:https://api.proxycraw.com|accept-language:en-GB' }).body)
=> {"headers"=>{
  ...
  "Accept-Language"=>"en-GB",
  "Referer"=>"https://api.proxycraw.com"
  ...
}}
```
